name    'grahamgilbert-mac_facts'
version '0.5.0'
author 'grahamgilbert'
license 'Apache License, Version 2.0'
summary 'A collection of Facts to aid with the administration of OS X machines'
description 'Some simple Facts that may help with configuring OS X client machines'
project_page 'https://github.com/grahamgilbert/grahamgilbert-mac_facts'
